### PR TITLE
Omit mkPolyline from tvOS 8, watchOS builds

### PR DESCRIPTION
**Pull request by 1ec5**
Fixed the following compilation errors on tvOS and watchOS introduced by #39:

```
/path/to/Polyline/Polyline/Polyline.swift
/path/to/Polyline/Polyline/Polyline.swift:59:28: 'MKPolyline' is only available on tvOS 9.2 or newer
/path/to/Polyline/Polyline/Polyline.swift:59:28: Add @available attribute to enclosing var
/path/to/Polyline/Polyline/Polyline.swift:59:28: Add @available attribute to enclosing struct
/path/to/Polyline/Polyline/Polyline.swift:61:26: 'MKPolyline' is only available on tvOS 9.2 or newer
/path/to/Polyline/Polyline/Polyline.swift:61:26: Add 'if #available' version check
/path/to/Polyline/Polyline/Polyline.swift:61:26: Add @available attribute to enclosing var
/path/to/Polyline/Polyline/Polyline.swift:61:26: Add @available attribute to enclosing struct
```

```
/path/to/Polyline/Polyline/Polyline.swift
/path/to/Polyline/Polyline/Polyline.swift:59:28: Use of undeclared type 'MKPolyline'
/path/to/Polyline/Polyline/Polyline.swift:61:26: Use of unresolved identifier 'MKPolyline'
/path/to/Polyline/Polyline/Polyline.swift:59:16: Did you mean 'mkPolyline'?
/path/to/Polyline/Polyline/Polyline.swift:41:15: Did you mean 'Polyline'?
```

/cc @tomtaylor @frederoni

### CODE REVIEW

**Comment by 1ec5** [comment]
@tomtaylor @raphaelmor, can you take a look? (For what it’s worth, I’d be happy to help out as a collaborator, since I maintain some libraries that depend on this library.)

**Comment by raphaelmor** [comment]
I'm adding you as a collaborator, if @tomtaylor is fine with, the more the merrier (and I can't contribute anymore :( )

**Comment by tomtaylor** [comment]
Absolutely!

**Comment by 1ec5** [comment]
Thanks!
