### ISSUE TITLE
Swift 3.1 compile warning — 'unsafeBitCast' from 'UnsafeRawPointer' to 'UnsafePointer<Int8>'

### ISSUE THREAD

**Issue by erichoracek** [raphaelmor/Polyline#42]
In the latest Xcode 8.3 beta, I'm getting the following error on line:

https://github.com/raphaelmor/Polyline/blob/master/Polyline/Polyline.swift#L171

```
let byteArray = unsafeBitCast((data as NSData).bytes, to: UnsafePointer<Int8>.self)
``` 

```
Polyline.swift:160:21: error: 'unsafeBitCast' from 'UnsafeRawPointer' to 'UnsafePointer<Int8>' gives a type to a raw pointer and may lead to undefined behavior
    let byteArray = unsafeBitCast((data as NSData).bytes, to: UnsafePointer<Int8>.self)
                    ^
Polyline.swift:160:21: note: use the 'assumingMemoryBound' method if the pointer is known to point to an existing value or array of type 'Int8' in memory
    let byteArray = unsafeBitCast((data as NSData).bytes, to: UnsafePointer<Int8>.self)
                    ^~~~~~~~~~~~~~                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                        .assumingMemoryBound(to: Int8.self)
Polyline.swift:160:21: note: use the 'bindMemory' method to assign type 'Int8' to uninitialized raw memory
    let byteArray = unsafeBitCast((data as NSData).bytes, to: UnsafePointer<Int8>.self)
                    ^~~~~~~~~~~~~~                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                        .bindMemory(to: Int8.self, capacity: <#capacity#>)
```

The compiler is suggesting it should be rewritten as:

```
let byteArray = (data as NSData).bytes.assumingMemoryBound(to: Int8.self)
```

Does this seem reasonable? I can open a pull request with these changes if desired.

**Comment by erichoracek** [comment]
This change does compile on Xcode 8.2, so it appears to be backwards-compatible with Swift 3.0.

**Comment by 1ec5** [comment]
Sure, a PR would be great!

**Comment by 1ec5** [comment]
Looks like there’s also [a longstanding to-do](https://github.com/raphaelmor/Polyline/blob/c54b1d31c9d227b0fa9a51b66ae53dd7503ce51f/Polyline/Polyline.swift#L290) to revisit whether an UnsafePointer is needed, or whether a standard `[Int8]` is performant enough.
